service: rest-endpoint

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"

  apiGateway:
    shouldStartNameWithService: true
    apiKeys:
      - name: rest-endpoint-apikey
        value: ${env:API_KEY, ''}

functions:
  endpoint:
    handler: endpoint.default
    maximumRetryAttempts: 0
    events:
      - http:
          method: POST
          path: /endpoint

resources:
  Outputs:
    apiKeyId:
      Value: !Ref ApiGatewayApiKey1
